services:
  frontend:
    build:
      context: ./todo-frontend
    environment:
      - VITE_BACKEND_URL=/api
    container_name: prod-todo-front
    depends_on:
      - backend
  backend:
    build:
      context: ./todo-backend
    environment:
      MONGO_URL: "mongodb://the_username:the_password@mongo:27017/the_database"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
